// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXwr7qT1t_7VtUW_53SFyeHbbuC5WtOY',
    appId: '1:962548262771:web:78e8b85aa068d36353c706',
    messagingSenderId: '962548262771',
    projectId: 'sandy-ae40f',
    authDomain: 'sandy-ae40f.firebaseapp.com',
    storageBucket: 'sandy-ae40f.appspot.com',
    measurementId: 'G-EGZLVYSB3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlXj7RgaqpMdgs3z-9xYyI6v2JdfPAFw',
    appId: '1:962548262771:android:e16f1a02acff701b53c706',
    messagingSenderId: '962548262771',
    projectId: 'sandy-ae40f',
    storageBucket: 'sandy-ae40f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Si76Bo-ICe4q6mAQ7J3NxEFTOKV1Iso',
    appId: '1:962548262771:ios:6121597279cb2ec353c706',
    messagingSenderId: '962548262771',
    projectId: 'sandy-ae40f',
    storageBucket: 'sandy-ae40f.appspot.com',
    iosClientId: '962548262771-8adec7h741fpgpcpm0qktj548v56mcn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Si76Bo-ICe4q6mAQ7J3NxEFTOKV1Iso',
    appId: '1:962548262771:ios:6121597279cb2ec353c706',
    messagingSenderId: '962548262771',
    projectId: 'sandy-ae40f',
    storageBucket: 'sandy-ae40f.appspot.com',
    iosClientId: '962548262771-8adec7h741fpgpcpm0qktj548v56mcn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandy',
  );
}
